Added CI Latest images can be built independently

diff --git a/fsharp/latest/Dockerfile b/fsharp/latest/Dockerfile
--- a/fsharp/latest/Dockerfile
+++ b/fsharp/latest/Dockerfile
@@ -1,1 +1,43 @@
-FROM nimashoghi/fsharp:netcoreapp2.2
+FROM mcr.microsoft.com/dotnet/core/sdk:latest
+
+# Copy endpoint specific user settings into container to specify
+# .NET Core should be used as the runtime.
+COPY settings.vscode.json /root/.vscode-remote/data/Machine/settings.json
+
+# Install git, process tools
+RUN apt-get update && apt-get -y install git procps
+
+# Install Docker CE CLI
+RUN apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common lsb-release \
+    && curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
+    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" \
+    && apt-get update \
+    && apt-get install -y docker-ce-cli
+
+RUN mkdir /workspace
+WORKDIR /workspace
+
+# Install paket
+RUN dotnet tool install --global Paket
+
+# Install fake
+RUN dotnet tool install --global fake-cli
+
+# Add fsi to PATH
+COPY fsi /root/.dotnet/tools/fsi
+
+# Add dotnet tools to PATH
+ENV PATH="/root/.dotnet/tools/:${PATH}"
+
+# Fix problems with locale
+RUN apt-get update \
+    && apt-get install --yes locales \
+    && echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
+    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
+    && echo "LANG=en_US.UTF-8" > /etc/locale.conf \
+    && locale-gen en_US.UTF-8
+
+# Clean up
+RUN apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
diff --git a/node/latest/Dockerfile b/node/latest/Dockerfile
--- a/node/latest/Dockerfile
+++ b/node/latest/Dockerfile
@@ -1,1 +1,36 @@
-FROM nimashoghi/node:current
+FROM node:current
+
+# Configure apt
+ENV DEBIAN_FRONTEND=noninteractive
+RUN apt-get update \
+    && apt-get -y install --no-install-recommends apt-utils 2>&1
+
+# Verify git and needed tools are installed
+RUN apt-get install -y git procps
+
+# Install Docker CE CLI
+RUN apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common lsb-release \
+    && curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
+    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" \
+    && apt-get update \
+    && apt-get install -y docker-ce-cli
+
+# Remove outdated yarn from /opt and install via package
+# so it can be easily updated via apt-get upgrade yarn
+RUN rm -rf /opt/yarn-* \
+    && rm -f /usr/local/bin/yarn \
+    && rm -f /usr/local/bin/yarnpkg \
+    && apt-get install -y curl apt-transport-https lsb-release \
+    && curl -sS https://dl.yarnpkg.com/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/pubkey.gpg | apt-key add - 2>/dev/null \
+    && echo "deb https://dl.yarnpkg.com/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
+    && apt-get update \
+    && apt-get -y install --no-install-recommends yarn
+
+# Install tslint and typescript
+RUN npm install -g tslint typescript
+
+# Clean up
+RUN apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
+ENV DEBIAN_FRONTEND=dialog
diff --git a/powershell/latest/Dockerfile b/powershell/latest/Dockerfile
--- a/powershell/latest/Dockerfile
+++ b/powershell/latest/Dockerfile
@@ -1,1 +1,39 @@
-FROM nimashoghi/powershell:6.2.0
+FROM debian:stretch
+
+# Copy endpoint specific user settings into container to specify
+# .NET Core should be used as the runtime.
+COPY settings.vscode.json /root/.vscode-remote/data/Machine/settings.json
+
+# Install git, process tools
+RUN apt-get update && apt-get -y install git procps
+
+# Install Docker CE CLI
+RUN apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common lsb-release \
+    && curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
+    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" \
+    && apt-get update \
+    && apt-get install -y docker-ce-cli
+
+# Install PowerShell and set PowerShell as default shell
+RUN apt-get update \
+    && apt-get install -y curl gnupg apt-transport-https \
+    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
+    && sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list' \
+    && apt-get update \
+    && apt-get install -y powershell
+
+RUN mkdir /workspace
+WORKDIR /workspace
+
+# Fix problems with locale
+RUN apt-get update \
+    && apt-get install --yes locales \
+    && echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
+    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
+    && echo "LANG=en_US.UTF-8" > /etc/locale.conf \
+    && locale-gen en_US.UTF-8
+
+# Clean up
+RUN apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
diff --git a/python/latest/Dockerfile b/python/latest/Dockerfile
--- a/python/latest/Dockerfile
+++ b/python/latest/Dockerfile
@@ -1,1 +1,47 @@
-FROM nimashoghi/python:3.7
+FROM python:3.7-stretch
+
+# Copy default endpoint specific user settings overrides into container to specify Python path
+COPY settings.vscode.json /root/.vscode-remote/data/Machine/settings.json
+
+# Install git, process tools
+RUN apt-get update && apt-get -y install git procps
+
+# Install Docker CE CLI
+RUN apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common lsb-release \
+    && curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
+    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" \
+    && apt-get update \
+    && apt-get install -y docker-ce-cli
+
+# Install poetry
+RUN pip install --pre poetry \
+    && mkdir /root/.config \
+    && mkdir /root/.config/pypoetry \
+    && touch /root/.config/pypoetry/config.toml \
+    && poetry config settings.virtualenvs.create false
+
+# Install Jupyter
+RUN pip install jupyter
+
+# Install pylint
+RUN pip install pylint
+
+# Install black
+RUN pip install --pre black
+
+# Install mypy
+RUN pip install mypy
+
+# Install bandit
+RUN pip install bandit
+
+# Install bandit
+RUN pip install flake8
+
+RUN mkdir /workspace
+WORKDIR /workspace
+
+# Clean up
+RUN apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
